[workspace]
members = [ 
    "network",
    "network-wasm", 
    "server",
    "state-wasm", 
]

[profile.release]
opt-level = 3
panic = "unwind"
debug = true

[profile.dev]
panic = "unwind"

[toolchain]
components = [ "rust-src" ]